sudo: false
language: node_js
node_js:
- '8'
matrix:
  fast_finish: true
  allow_failures: []
cache: yarn
install:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/2d86ca6ebe8730048750eeeb3845e8857dc89aa0/scripts/node-install.bash)"
before_script:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/2d86ca6ebe8730048750eeeb3845e8857dc89aa0/scripts/node-verify.bash)"
notifications:
  email:
    recipients:
      secure: MTTh5MOVL9zgohXTYg5HEcWIzIg9NcZskP/AyWRSpGEwSLbfWNONQqcHLapyuTGUSKqTpJjKlS6pnpRnMXawHWqP3zAfwxuOppkaPkCeoB5FcC1LvDpnBqU99F/vS3aflChnVRYu0ZkSZgEmfowmzAiXhRSGFTO2CN3C1GC8O4geqsuIivZ/0IIordiyPXe1UkKuBwYy3sEiF282F5gKc39gOPdr7MXvXj+NGmIOlLQDv9v/q+XAz6lVKp6fs78CPqzfZB0J/PyYrX5757nzm18xTALMbfEF3dmimdayjrrVrpsZ1iQYIoSeNXsFjXzMeBNS5bWDRIa4ckurwvmvJuI4kBTlLsMOKopquqQE1p2M4jPdB1TWu6m51csZbHRKVleXLC3YK0SVEew8EBaDa7Ha8KN0il7O/aGoG0bYTQwpp67PR7uRetqaKxOZ0ik9m5arF4ZWGMIRe68nPfbE2Ne+Jm3opKmf+1ekjMRg6Alj11T7D6PTBa36wfD+tf0MTRqCmyysTnmelp6SgRWx3RhXDmOrKf5xouHrU7ylZ7utN65uc6Vu5Wu1cqZrk02QICAd4BYha0F0jbh7Bzu7a5oD4j31uI4uVdqvxjSVy2NuWLmPsNTcyE8vGzczj9rS06We3K9WFLycTvUXa/0AtbmP605EZqoPxKPgMX/epKc=
