sudo: false
language: node_js
node_js:
- '8'
matrix:
  fast_finish: true
  allow_failures: []
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.yarn-cache"
install:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/1ec050bc004d0e2161cb5286c247850d24aecc02/scripts/node-install.bash)"
before_script:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/1ec050bc004d0e2161cb5286c247850d24aecc02/scripts/node-verify.bash)"
after_success:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/1ec050bc004d0e2161cb5286c247850d24aecc02/scripts/deploy-custom.bash)"
notifications:
  slack:
    secure: iHdN95qboy3YxDUoE4cCHBOlsCYi3V51sa1oPstIY6+9q1PUKs8mt0W9MiFZVHUQcfsqBPUvDbPDGebXE0MkoNL57gqrvJoD2Vf38zOnbZrHQcBRvwBiprIn+opE03Wo7+qk4wVYLYmyh+JnX6+r6TUs9Cr3Gg1f/O1LuVUiZrjbbYUBSRSU1XTsdrKqlyEsHREwb9dH4t3reqbnC8i9am25MD2ProWzDnkrPAD0ZXTJOOtuVsdhAIpgNJcoRVb9QUdE56vtrbBrHJmi8F6dh3Z3w3zzzZaaRzndPnibLMxcZol7kWzE4LVBiE0SZJSK4rt57bhTwUYHWMMW/fb+2zzloaIs5H2rTz+5wnBV37ZyKQOuOyq0Tld17RaN8pMKwHJxat1/sLD8XGtSGmReqt4R4e+l7al7vHF5KEkp7gAh4ANtSSskm+s7tDNDVu5n0O70wYzVHH5Is3jii2nDPBEL2Jv8Kmg0rolvpkT69LnNtGAzqhV38IzotsH1kiPxq/sumxf5xkqXRzq0jVUJSjCD2ul3+XZv9VeooBuAhlgmEQZ0YRt+LBgZsyQgqu9CKPo4QPbraLHgIScRXtS4LX/ySbuXvj77A9KYyvlH48TqjX564Kw3X71Op5CoRsP6QN70++wJOY8ivujma+sAf1LXYtEg+CnWrkRPPKBlYN8=
  email:
    recipients:
      secure: APpKN6RIIpahwi+yCnusQ2WK2x//1I4FEt6QZxPLPPFyh3rbatzrPJgmLnkrJXCh68eW5VBHgWCQpfqGdxVQXoeb+MDQBBhdwwtHqGkIIT7gIn47zr/zjjPKQFpHw3BzXgn8KEdSyJyjT7oTitoa80Vy3U7BCQC+Bt80hPatSXByyOKlbt+JCtJxRq6doNFEu9hlulgo/cmsmkYmP+4VVE7BJsYFJMA1TkoWfl7rfIOi4SZCW/lCTYHfKxbX4PR3kZ04D9J4/DXqNARisATf0Jv4IuK+XNtg+XaQVMsoA+V1H5b0+kLKFXZTPN+w3aL+qyNk8RyzA8RyqZm4P+gjmlUHdvpBDjkdzkYVhPOfW2fP2sgWg/1YQjZ4LEFlrRMGHkbtzNNLqE0aM1KsTZQuL5Aio/QT2G4wuVj7FKkPGwGK///9noV2R31D+9gH5M9bXOiLohP3iCvHT9JMPmsgFRcGUjhciBKKwEfZarM6XuOW336hjemxFWo1BP+lFH+KcRcXFXDEQeTIRMsdgA5Jnt/ZalRwnLq9U810KpT+CepT0cZOVgBQ28+Meq7pzoqYRJUCuFv8dO9zGonr/xajVF8aA1wo/t/dFThHW7DtlIZWtcyt48a/ELUYiawl62vRD9xd3PUjAJ89GZbpPPQ+Qb09D8KD/sOyvFBrel/VGjU=
